name: Build against OSGeo4W packages

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  root:
    concurrency:
      group: >-
        ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}-${{
        'root-dir-variations' }}-${{  matrix.os }}-${{ matrix.root-dir }}-${{ matrix.pkg-dir }}
      cancel-in-progress: true
    runs-on: ${{ matrix.os }}
    env:
      TEST_O4W_ROOT: ${{ matrix.root-dir }}
    strategy:
      matrix:
        os:
          # - windows-2019
          # - windows-2022
          - windows-latest
        root-dir:
          - "C:\\OSGeo4W"
          # - "D:\\OSGeo4W"
          # - "D:/OSGeo4W"
          # - "C:/otherFolder/"
        pkg-dir:
          - "${{ github.workspace }}/OSGeo4W_pkg"
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup OSGeo4W environment
        id: setup-osgeo4w
        uses: ./
        with:
          root: ${{ matrix.root-dir }}
          package-dir: ${{ matrix.pkg-dir }}
          # Using line folding replacing newlines by a space, and striping the final newlines
          # See https://yaml-multiline.info/
          # packages: >-
          #   grass-dev
          #   saga
      - name: Display all outputs as JSON
        run: |
          echo "${{ toJSON(steps.setup-osgeo4w.outputs) }}"
      - name: Show OSGeo4W root
        run: echo "${{ steps.setup-osgeo4w.outputs.root }}"
      - run: o-help
        shell: cmd /D /E:ON /V:OFF /S /C "CALL %TEST_O4W_ROOT%/OSGeo4W.bat "{0}""
      - run: pip install pytest-timeout
        shell: cmd /D /E:ON /V:OFF /S /C "CALL %TEST_O4W_ROOT%/OSGeo4W.bat "{0}""
